f = open("C:\\Users\\nehaa\\OneDrive\\Documents\\neha\\python\\sample1.txt", "r")
print(f.read())
a = open("C:\\Users\\nehaa\\OneDrive\\Documents\\neha\\python\\sample1.txt","w")   
print(a.write("what you are"))
a.close()